CREATE TABLE IF NOT EXISTS SAMPLE ( ID BIGINT PRIMARY KEY, NAME TEXT);

--DROP SEQUENCE SAMPLE_SEQ;

CREATE SEQUENCE IF NOT EXISTS SAMPLE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 1000000 NOCYCLE NOCACHE;